name: Wake Up Streamlit App

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小時運行一次
  workflow_dispatch:  # 允許手動觸發
  push:
    branches: [ main ]  # 當推送到main分支時也觸發

jobs:
  wake_up:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
    
    - name: Run wake up script
      run: |
        python wake_up_streamlit.py
      env:
        PYTHONUNBUFFERED: 1
