name: Wake Up Streamlit App

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小時運行一次
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  wake_up:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        chromium-browser --version
        chromedriver --version
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.9.1 webdriver-manager==3.8.6
    
    - name: Run wake up script
      env:
        PYTHONUNBUFFERED: 1
        CHROME_BIN: /usr/bin/chromium-browser
        CHROMEDRIVER_PATH: /usr/bin/chromedriver
      run: python wake_up_streamlit.py
